const SEED_SITE_ID = process.env.E2E_SITE_ID ?? "550e8400-e29b-41d4-a716-446655440000";

const CREDENTIALS = {
  admin: {
    email: "admin.e2e@appquilar.test",
    password: "E2Epass!123",
  },
  company_admin: {
    email: "company.admin.e2e@appquilar.test",
    password: "E2Epass!123",
  },
  user: {
    email: "user.e2e@appquilar.test",
    password: "E2Epass!123",
  },
};

const USERS = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    first_name: "Ada",
    last_name: "Admin",
    email: CREDENTIALS.admin.email,
    password: CREDENTIALS.admin.password,
    roles: ["ROLE_ADMIN"],
    plan_type: "explorer",
    subscription_status: "active",
    product_slot_limit: 5,
    company_id: null,
    company_name: null,
    company_role: null,
    is_company_owner: false,
    company_context: null,
    status: "active",
    date_added: "2026-02-01T10:00:00Z",
    address: {
      street: "Calle Admin 1",
      street2: null,
      city: "Madrid",
      postal_code: "28001",
      state: "Madrid",
      country: "ES",
    },
    location: {
      latitude: 40.4168,
      longitude: -3.7038,
    },
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    first_name: "Carla",
    last_name: "Company",
    email: CREDENTIALS.company_admin.email,
    password: CREDENTIALS.company_admin.password,
    roles: ["ROLE_USER", "company_admin"],
    plan_type: "user_pro",
    subscription_status: "active",
    product_slot_limit: 12,
    company_id: "company-1",
    company_name: "Herramientas Norte",
    company_role: "ROLE_ADMIN",
    is_company_owner: true,
    company_plan_type: "pro",
    company_subscription_status: "active",
    company_is_founding_account: true,
    company_product_slot_limit: 30,
    company_context: {
      company_id: "company-1",
      company_name: "Herramientas Norte",
      company_role: "ROLE_ADMIN",
      is_company_owner: true,
      plan_type: "pro",
      subscription_status: "active",
      is_founding_account: true,
      product_slot_limit: 30,
    },
    status: "active",
    date_added: "2026-02-01T10:00:00Z",
    address: {
      street: "Avenida Empresa 12",
      street2: null,
      city: "Barcelona",
      postal_code: "08001",
      state: "Barcelona",
      country: "ES",
    },
    location: {
      latitude: 41.3874,
      longitude: 2.1686,
    },
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    first_name: "Uri",
    last_name: "User",
    email: CREDENTIALS.user.email,
    password: CREDENTIALS.user.password,
    roles: ["ROLE_USER"],
    plan_type: "explorer",
    subscription_status: "active",
    product_slot_limit: 3,
    company_id: null,
    company_name: null,
    company_role: null,
    is_company_owner: false,
    company_context: null,
    status: "active",
    date_added: "2026-02-01T10:00:00Z",
    address: {
      street: "Calle Usuario 8",
      street2: null,
      city: "Valencia",
      postal_code: "46001",
      state: "Valencia",
      country: "ES",
    },
    location: {
      latitude: 39.4699,
      longitude: -0.3763,
    },
  },
];

const COMPANIES = [
  {
    company_id: "company-1",
    owner_id: "22222222-2222-4222-8222-222222222222",
    name: "Herramientas Norte",
    slug: "herramientas-norte",
    description: "Alquiler profesional para obra y bricolaje.",
    fiscal_identifier: "B12345678",
    contact_email: "hola@herramientasnorte.test",
    phone_number: {
      country_code: "ES",
      prefix: "+34",
      number: "611000111",
    },
    address: {
      street: "Calle Taller 7",
      street2: null,
      city: "Barcelona",
      postal_code: "08001",
      state: "Barcelona",
      country: "ES",
    },
    location: {
      latitude: 41.39,
      longitude: 2.17,
    },
    plan_type: "pro",
    subscription_status: "active",
    is_founding_account: true,
  },
  {
    company_id: "company-2",
    owner_id: "11111111-1111-4111-8111-111111111111",
    name: "Logistica Sur",
    slug: "logistica-sur",
    description: "Equipos de transporte y logistica.",
    fiscal_identifier: "B87654321",
    contact_email: "hola@logisticasur.test",
    phone_number: {
      country_code: "ES",
      prefix: "+34",
      number: "622000111",
    },
    address: {
      street: "Calle Puerto 21",
      street2: null,
      city: "Sevilla",
      postal_code: "41001",
      state: "Sevilla",
      country: "ES",
    },
    location: {
      latitude: 37.3891,
      longitude: -5.9845,
    },
    plan_type: "starter",
    subscription_status: "paused",
    is_founding_account: false,
  },
];

const COMPANY_USERS = [
  {
    company_id: "company-1",
    user_id: "22222222-2222-4222-8222-222222222222",
    email: CREDENTIALS.company_admin.email,
    role: "ROLE_ADMIN",
    status: "ACCEPTED",
  },
  {
    company_id: "company-1",
    user_id: "33333333-3333-4333-8333-333333333333",
    email: CREDENTIALS.user.email,
    role: "ROLE_CONTRIBUTOR",
    status: "PENDING",
  },
];

const CATEGORIES = [
  {
    id: "cat-1",
    name: "Herramientas",
    slug: "herramientas",
    description: "Herramientas electricas y manuales.",
    parent_id: null,
    icon_id: null,
    featured_image_id: null,
    landscape_image_id: null,
  },
  {
    id: "cat-2",
    name: "Construccion",
    slug: "construccion",
    description: "Equipos de construccion.",
    parent_id: null,
    icon_id: null,
    featured_image_id: null,
    landscape_image_id: null,
  },
  {
    id: "cat-3",
    name: "Movilidad",
    slug: "movilidad",
    description: "Vehiculos ligeros.",
    parent_id: null,
    icon_id: null,
    featured_image_id: null,
    landscape_image_id: null,
  },
  {
    id: "cat-4",
    name: "Taladros",
    slug: "taladros",
    description: "Taladros y accesorios.",
    parent_id: "cat-1",
    icon_id: null,
    featured_image_id: null,
    landscape_image_id: null,
  },
];

const SITE = {
  site_id: SEED_SITE_ID,
  name: "Appquilar",
  title: "Appquilar",
  url: "http://localhost:4173",
  description: "Marketplace de alquiler profesional",
  logo_id: null,
  favicon_id: null,
  primary_color: "#1D4ED8",
  category_ids: ["cat-1", "cat-2", "cat-3", "cat-4"],
  menu_category_ids: ["cat-1", "cat-2", "cat-3"],
  featured_category_ids: ["cat-1", "cat-4"],
};

const PRODUCTS = [
  {
    id: "product-1",
    product_id: "product-1",
    internal_id: "PRD-001",
    name: "Taladro percutor 18V",
    slug: "taladro-percutor-18v",
    description: "Taladro profesional para uso continuo.",
    publication_status: "published",
    image_ids: [],
    deposit: { amount: 15000, currency: "EUR" },
    tiers: [
      {
        days_from: 1,
        days_to: 5,
        price_per_day: { amount: 2500, currency: "EUR" },
      },
      {
        days_from: 6,
        days_to: 30,
        price_per_day: { amount: 1900, currency: "EUR" },
      },
    ],
    categories: [{ id: "cat-4", name: "Taladros", slug: "taladros" }],
    category_id: "cat-4",
    owner_data: {
      owner_id: "company-1",
      type: "company",
      name: "Herramientas Norte",
      address: {
        street: "Calle Taller 7",
        street2: null,
        city: "Barcelona",
        postal_code: "08001",
        state: "Barcelona",
        country: "ES",
      },
      geo_location: {
        latitude: 41.39,
        longitude: 2.17,
        circle: [],
      },
    },
  },
  {
    id: "product-2",
    product_id: "product-2",
    internal_id: "PRD-002",
    name: "Martillo demoledor",
    slug: "martillo-demoledor",
    description: "Equipo de alto impacto para obras.",
    publication_status: "published",
    image_ids: [],
    deposit: { amount: 35000, currency: "EUR" },
    tiers: [
      {
        days_from: 1,
        days_to: 5,
        price_per_day: { amount: 4200, currency: "EUR" },
      },
      {
        days_from: 6,
        days_to: 30,
        price_per_day: { amount: 3200, currency: "EUR" },
      },
    ],
    categories: [{ id: "cat-2", name: "Construccion", slug: "construccion" }],
    category_id: "cat-2",
    owner_data: {
      owner_id: "company-1",
      type: "company",
      name: "Herramientas Norte",
      address: {
        street: "Calle Taller 7",
        street2: null,
        city: "Barcelona",
        postal_code: "08001",
        state: "Barcelona",
        country: "ES",
      },
      geo_location: {
        latitude: 41.39,
        longitude: 2.17,
        circle: [],
      },
    },
  },
  {
    id: "product-3",
    product_id: "product-3",
    internal_id: "PRD-003",
    name: "Escalera telescopica",
    slug: "escalera-telescopica",
    description: "Escalera ligera para uso domestico y profesional.",
    publication_status: "draft",
    image_ids: [],
    deposit: { amount: 9000, currency: "EUR" },
    tiers: [
      {
        days_from: 1,
        days_to: 15,
        price_per_day: { amount: 1200, currency: "EUR" },
      },
    ],
    categories: [{ id: "cat-1", name: "Herramientas", slug: "herramientas" }],
    category_id: "cat-1",
    owner_data: {
      owner_id: "33333333-3333-4333-8333-333333333333",
      type: "user",
      name: "Uri User",
      address: {
        street: "Calle Usuario 8",
        street2: null,
        city: "Valencia",
        postal_code: "46001",
        state: "Valencia",
        country: "ES",
      },
      geo_location: {
        latitude: 39.4699,
        longitude: -0.3763,
        circle: [],
      },
    },
  },
];

const RENTS = [
  {
    rent_id: "rent-1",
    product_id: "product-1",
    product_name: "Taladro percutor 18V",
    product_slug: "taladro-percutor-18v",
    product_internal_id: "PRD-001",
    owner_id: "company-1",
    owner_type: "company",
    owner_name: "Herramientas Norte",
    renter_id: "33333333-3333-4333-8333-333333333333",
    renter_name: "Uri User",
    renter_email: CREDENTIALS.user.email,
    start_date: "2026-02-20",
    end_date: "2026-02-24",
    deposit: { amount: 15000, currency: "EUR" },
    price: { amount: 10000, currency: "EUR" },
    status: "proposal_pending_renter",
    is_lead: true,
    owner_proposal_accepted: true,
    renter_proposal_accepted: false,
    proposal_valid_until: "2026-03-10",
  },
  {
    rent_id: "rent-2",
    product_id: "product-2",
    product_name: "Martillo demoledor",
    product_slug: "martillo-demoledor",
    product_internal_id: "PRD-002",
    owner_id: "company-1",
    owner_type: "company",
    owner_name: "Herramientas Norte",
    renter_id: "33333333-3333-4333-8333-333333333333",
    renter_name: "Uri User",
    renter_email: CREDENTIALS.user.email,
    start_date: "2026-02-15",
    end_date: "2026-02-18",
    deposit: { amount: 35000, currency: "EUR" },
    price: { amount: 16800, currency: "EUR" },
    status: "rental_completed",
    is_lead: false,
    owner_proposal_accepted: true,
    renter_proposal_accepted: true,
    proposal_valid_until: null,
  },
  {
    rent_id: "rent-3",
    product_id: "product-1",
    product_name: "Taladro percutor 18V",
    product_slug: "taladro-percutor-18v",
    product_internal_id: "PRD-001",
    owner_id: "company-1",
    owner_type: "company",
    owner_name: "Herramientas Norte",
    renter_id: "11111111-1111-4111-8111-111111111111",
    renter_name: "Ada Admin",
    renter_email: CREDENTIALS.admin.email,
    start_date: "2026-03-05",
    end_date: "2026-03-07",
    deposit: { amount: 15000, currency: "EUR" },
    price: { amount: 7500, currency: "EUR" },
    status: "rental_confirmed",
    is_lead: false,
    owner_proposal_accepted: true,
    renter_proposal_accepted: true,
    proposal_valid_until: null,
  },
  {
    rent_id: "rent-4",
    product_id: "product-3",
    product_name: "Escalera telescopica",
    product_slug: "escalera-telescopica",
    product_internal_id: "PRD-003",
    owner_id: "33333333-3333-4333-8333-333333333333",
    owner_type: "user",
    owner_name: "Uri User",
    renter_id: "11111111-1111-4111-8111-111111111111",
    renter_name: "Ada Admin",
    renter_email: CREDENTIALS.admin.email,
    start_date: "2026-01-10",
    end_date: "2026-01-12",
    deposit: { amount: 9000, currency: "EUR" },
    price: { amount: 3600, currency: "EUR" },
    status: "cancelled",
    is_lead: true,
    owner_proposal_accepted: false,
    renter_proposal_accepted: false,
    proposal_valid_until: null,
  },
];

const RENT_MESSAGES = {
  "rent-1": [
    {
      message_id: "msg-1",
      rent_id: "rent-1",
      sender_role: "renter",
      sender_name: "Uri User",
      content: "Hola, puedo recogerlo manana?",
      created_at: "2026-03-01 10:00:00",
      is_mine: false,
    },
    {
      message_id: "msg-2",
      rent_id: "rent-1",
      sender_role: "owner",
      sender_name: "Herramientas Norte",
      content: "Si, sin problema.",
      created_at: "2026-03-01 10:05:00",
      is_mine: true,
    },
  ],
  "rent-2": [
    {
      message_id: "msg-3",
      rent_id: "rent-2",
      sender_role: "owner",
      sender_name: "Herramientas Norte",
      content: "Alquiler completado. Gracias.",
      created_at: "2026-02-18 18:00:00",
      is_mine: true,
    },
  ],
  "rent-3": [
    {
      message_id: "msg-4",
      rent_id: "rent-3",
      sender_role: "renter",
      sender_name: "Ada Admin",
      content: "Confirmo las fechas.",
      created_at: "2026-03-02 09:30:00",
      is_mine: false,
    },
  ],
  "rent-4": [],
};

const UNREAD_BY_RENT = {
  "rent-1": 2,
  "rent-2": 0,
  "rent-3": 1,
  "rent-4": 0,
};

const COMPANY_STATS = {
  "company-1": {
    company_id: "company-1",
    period: { from: "2026-02-01", to: "2026-03-03" },
    summary: {
      total_views: 420,
      unique_visitors: 210,
      repeat_visitors: 56,
      repeat_visitor_ratio: 0.266,
      logged_views: 180,
      anonymous_views: 240,
      messages_total: 33,
      message_threads: 17,
      message_to_rental_ratio: 0.21,
      average_first_response_minutes: 18,
    },
    top_locations: [
      {
        country: "ES",
        region: "Catalonia",
        city: "Barcelona",
        total_views: 120,
        unique_visitors: 70,
      },
      {
        country: "ES",
        region: "Madrid",
        city: "Madrid",
        total_views: 90,
        unique_visitors: 54,
      },
    ],
    series: {
      daily_views: [
        { day: "2026-02-26", views: 10 },
        { day: "2026-02-27", views: 17 },
        { day: "2026-02-28", views: 13 },
        { day: "2026-03-01", views: 22 },
        { day: "2026-03-02", views: 30 },
        { day: "2026-03-03", views: 27 },
      ],
      daily_messages: [
        { day: "2026-02-26", messages: 2 },
        { day: "2026-02-27", messages: 3 },
        { day: "2026-02-28", messages: 2 },
        { day: "2026-03-01", messages: 4 },
        { day: "2026-03-02", messages: 5 },
        { day: "2026-03-03", messages: 4 },
      ],
    },
    by_product: [
      {
        product_id: "product-1",
        product_name: "Taladro percutor 18V",
        product_slug: "taladro-percutor-18v",
        total_views: 230,
        unique_visitors: 130,
        logged_views: 110,
        anonymous_views: 120,
        messages_total: 18,
        message_threads: 10,
        visit_to_message_ratio: 0.078,
        message_to_rental_ratio: 0.24,
      },
      {
        product_id: "product-2",
        product_name: "Martillo demoledor",
        product_slug: "martillo-demoledor",
        total_views: 190,
        unique_visitors: 80,
        logged_views: 70,
        anonymous_views: 120,
        messages_total: 15,
        message_threads: 7,
        visit_to_message_ratio: 0.078,
        message_to_rental_ratio: 0.18,
      },
    ],
    opportunities: {
      high_interest_low_conversion: {
        product_id: "product-2",
        product_name: "Martillo demoledor",
        product_slug: "martillo-demoledor",
        total_views: 190,
        unique_visitors: 80,
        logged_views: 70,
        anonymous_views: 120,
        messages_total: 15,
        message_threads: 7,
        visit_to_message_ratio: 0.078,
        message_to_rental_ratio: 0.18,
      },
    },
  },
};

const USER_STATS = {
  "33333333-3333-4333-8333-333333333333": {
    user_id: "33333333-3333-4333-8333-333333333333",
    period: { from: "2026-02-01", to: "2026-03-03" },
    summary: {
      total_views: 80,
      unique_visitors: 47,
      messages_total: 9,
      message_threads: 5,
    },
    series: {
      daily_views: [
        { day: "2026-02-27", views: 3 },
        { day: "2026-02-28", views: 5 },
        { day: "2026-03-01", views: 4 },
        { day: "2026-03-02", views: 7 },
        { day: "2026-03-03", views: 6 },
      ],
      daily_messages: [
        { day: "2026-02-27", messages: 1 },
        { day: "2026-02-28", messages: 1 },
        { day: "2026-03-01", messages: 2 },
        { day: "2026-03-02", messages: 3 },
        { day: "2026-03-03", messages: 2 },
      ],
    },
    by_product: [
      {
        product_id: "product-3",
        product_name: "Escalera telescopica",
        product_slug: "escalera-telescopica",
        total_views: 80,
        unique_visitors: 47,
        messages_total: 9,
        message_threads: 5,
      },
    ],
  },
};

const BLOG_STATE = {
  posts: [],
  categories: [],
};

const transparentPngBase64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAEAgH/6sQ35QAAAABJRU5ErkJggg==";

const templateState = {
  site: SITE,
  users: USERS,
  companies: COMPANIES,
  companyUsers: COMPANY_USERS,
  categories: CATEGORIES,
  products: PRODUCTS,
  rents: RENTS,
  rentMessages: RENT_MESSAGES,
  unreadByRent: UNREAD_BY_RENT,
  companyStats: COMPANY_STATS,
  userStats: USER_STATS,
  blog: BLOG_STATE,
};

const clone = (value) => JSON.parse(JSON.stringify(value));

export const createInitialSeedState = () => clone(templateState);

export const seedConfig = {
  siteId: SEED_SITE_ID,
  credentials: CREDENTIALS,
  transparentPngBase64,
};

