import * as Bi from 'react-icons/bi';
import * as Fa from 'react-icons/fa';
import * as Hi from 'react-icons/hi';
import * as Md from 'react-icons/md';
import * as Io from 'react-icons/io';
import * as Fi from 'react-icons/fi';
import {
  Camera, 
  Music, 
  Image, 
  Video, 
  FileVideo,
  Film,
  Monitor,
  Tv,
  Desktop,
  Laptop,
  Phone,
  Tablet,
  Smartphone,
  Speaker,
  Headphones,
  Radio,
  Mic,
  Book,
  Library,
  Files,
  Folder,
  Box,
  Archive,
  Save,
  Upload,
  Download,
  Cloud,
  Globe,
  Map,
  MapPin,
  Navigation,
  Flag,
  Car,
  Truck,
  Bus,
  Train,
  Plane,
  Bicycle,
  Tools,
  Settings,
  Wrench,
  Screwdriver,
  Scissors,
  PenTool,
  Brush,
  Palette,
  Grid,
  Layout,
  Sidebar,
  Layers,
  Filter,
  Magic,
  Wand,
  Star,
  Heart,
  Trophy,
  Award,
  Gift,
  Package,
  ShoppingBag,
  ShoppingCart,
  CreditCard,
  Wallet,
  DollarSign,
  Receipt,
  ChartBar,
  ChartLine,
  ChartPie,
  Activity,
  Pulse,
  Thermometer,
  Droplet,
  Database,
  Server,
  Terminal,
  Code,
  Cpu,
  Chip,
  Battery,
  Plug,
  Wifi,
  Bluetooth,
  Signal,
  Power,
  Mail,
  MessageCircle,
  MessageSquare,
  Send,
  Share,
  Link,
  LinkUnlink,
  Paperclip,
  Hash,
  List,
  ListChecks,
  CheckSquare,
  Check,
  X,
  Plus,
  Minus,
  Divide,
  Equal,
  Percent,
  AtSign,
  Search,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Expand,
  Shrink,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Calendar,
  Bell,
  Info,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Help,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Cog,
  Settings2,
  User,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX
} from 'lucide-react';

export const ICONS_MAP: Record<string, React.ComponentType<any>> = {
  // Tools and Equipment
  "tools": Fa.FaTools,
  "hammer": Fa.FaHammer,
  "wrench": Fa.FaWrench,
  "screwdriver": Fa.FaScrewdriver,
  "drill": Fa.FaDrumSteelpan,
  "toolbox": Fa.FaToolbox,
  "repair": Fa.FaWrench,
  "equipment": Fa.FaTools,

  // Electronics
  "electronics": Md.MdDevices,
  "laptop": Md.MdLaptopMac,
  "smartphone": Md.MdSmartphone,
  "camera": Md.MdCameraAlt,
  "tv": Md.MdTv,
  "computer": Md.MdComputer,
  "tablet": Md.MdTablet,
  "printer": Md.MdPrint,
  "phone": Md.MdPhone,
  "battery": Md.MdBattery90,
  "bluetooth": Md.MdBluetooth,
  "wifi": Md.MdWifi,

  // Garden and Outdoor
  "garden": Fa.FaSeedling,
  "tree": Fa.FaTree,
  "leaf": Fa.FaLeaf,
  "flower": Fa.FaSpa,
  "shovel": Fa.FaSpa,
  "rake": Fa.FaCanadianMapleLeaf,
  "lawnmower": Fa.FaLeaf,
  "watering": Fi.FiCloudRain,
  "plant": Fa.FaSeedling,
  "sun": Fa.FaSun,

  // Music and Audio
  "music": Fa.FaMusic,
  "guitar": Fa.FaGuitar,
  "headphones": Fa.FaHeadphones,
  "microphone": Fa.FaMicrophone,
  "piano": Fa.FaMusic,
  "drum": Fa.FaDrum,
  "speaker": Md.MdSpeaker,
  "volume": Fa.FaVolumeUp,
  "playlist": Fa.FaPlayCircle,
  "record": Fa.FaRecordVinyl,

  // Sports and Recreation
  "sports": Md.MdSportsBasketball,
  "basketball": Md.MdSportsBasketball,
  "football": Md.MdSportsSoccer,
  "baseball": Md.MdSportsBaseball,
  "tennis": Md.MdSportsTennis,
  "volleyball": Md.MdSportsVolleyball,
  "fitness": Md.MdFitnessCenter,
  "running": Fa.FaRunning,
  "swimming": Fa.FaSwimmer,
  "cycling": Fa.FaBiking,

  // Furniture
  "furniture": Md.MdChair,
  "chair": Md.MdChair,
  "table": Fa.FaTable,
  "bed": Md.MdBed,
  "sofa": Md.MdWeekend,
  "desk": Md.MdDesk,
  "cabinet": Md.MdStorage,
  "drawer": Md.MdStorage,
  "floor-lamp": Fa.FaLightbulb,
  "mirror": Md.MdOutlineMonitor,

  // Clothing and Accessories
  "clothing": Fa.FaTshirt,
  "shirt": Fa.FaTshirt,
  "pants": Fa.FaSocks,
  "dress": Fa.FaUserTie,
  "hat": Fa.FaHatCowboy,
  "shoes": Fa.FaShoePrints,
  "glasses": Fa.FaGlasses,
  "watch": Fa.FaClock,
  "ring": Fa.FaRing,
  "bag": Fa.FaShoppingBag,

  // Kitchen and Appliances
  "kitchen": Fa.FaUtensils,
  "blender": Fa.FaBlender,
  "refrigerator": Fa.FaSnowflake,
  "oven": Md.MdMicrowave,
  "utensils": Fa.FaUtensils,
  "coffee": Fa.FaCoffee,
  "mixer": Fa.FaBlender,
  "dish": Fa.FaUtensils,
  "glass": Fa.FaWineGlass,
  "bottle": Fa.FaWineBottle,

  // Home and Living
  "home": Fa.FaHome,
  "lamp": Fa.FaLightbulb,
  "clock": Fa.FaClock,
  "carpet": Md.MdCarpenter,
  "curtains": Md.MdCurtains,
  "door": Fa.FaDoorOpen,
  "window": Fa.FaWindowMaximize,
  "paint": Fa.FaPaintBrush,
  "book": Fa.FaBook,
  "picture": Fa.FaImage,

  // Party and Events
  "party": Fa.FaGlassCheers,
  "balloons": Fa.FaBirthdayCake,
  "karaoke": Fa.FaMicrophone,
  "lights": Fa.FaLightbulb,
  "speaker-system": Md.MdSpeaker,
  "cake": Fa.FaBirthdayCake,
  "gift": Fa.FaGift,
  "celebration": Fa.FaGlassCheers,
  "confetti": Fa.FaStarAndCrescent,
  "dance": Fa.FaMusic,

  // Technology
  "robot": Fa.FaRobot,
  "code": Fa.FaCode,
  "database": Fa.FaDatabase,
  "server": Fa.FaServer,
  "cloud": Fa.FaCloud,
  "keyboard": Fa.FaKeyboard,
  "mouse": Fa.FaMouse,
  "network": Fa.FaNetworkWired,
  "security": Fa.FaShieldAlt,
  "settings": Fa.FaCog,

  // Transportation
  "car": Fa.FaCar,
  "bicycle": Fa.FaBicycle,
  "bus": Fa.FaBus,
  "train": Fa.FaTrain,
  "plane": Fa.FaPlane,
  "ship": Fa.FaShip,
  "motorcycle": Fa.FaMotorcycle,
  "truck": Fa.FaTruck,
  "helicopter": Fa.FaHelicopter,
  "rocket": Fa.FaRocket,

  // Lucide Media Icons
  'lucide-camera': Camera,
  'lucide-music': Music,
  'lucide-image': Image,
  'lucide-video': Video,
  'lucide-file-video': FileVideo,
  'lucide-film': Film,
  'lucide-monitor': Monitor,
  'lucide-tv': Tv,
  'lucide-desktop': Desktop,
  'lucide-laptop': Laptop,
  'lucide-phone': Phone,
  'lucide-tablet': Tablet,
  'lucide-smartphone': Smartphone,
  'lucide-speaker': Speaker,
  'lucide-headphones': Headphones,
  'lucide-radio': Radio,
  'lucide-mic': Mic,

  // Document & Storage
  'lucide-book': Book,
  'lucide-library': Library,
  'lucide-files': Files,
  'lucide-folder': Folder,
  'lucide-box': Box,
  'lucide-archive': Archive,
  'lucide-save': Save,
  'lucide-upload': Upload,
  'lucide-download': Download,

  // Navigation & Location
  'lucide-cloud': Cloud,
  'lucide-globe': Globe,
  'lucide-map': Map,
  'lucide-map-pin': MapPin,
  'lucide-navigation': Navigation,
  'lucide-flag': Flag,

  // Transportation
  'lucide-car': Car,
  'lucide-truck': Truck,
  'lucide-bus': Bus,
  'lucide-train': Train,
  'lucide-plane': Plane,
  'lucide-bicycle': Bicycle,

  // Tools & Settings
  'lucide-tools': Tools,
  'lucide-settings': Settings,
  'lucide-wrench': Wrench,
  'lucide-screwdriver': Screwdriver,
  'lucide-scissors': Scissors,
  'lucide-pen-tool': PenTool,
  'lucide-brush': Brush,
  'lucide-palette': Palette,

  // Layout & Design
  'lucide-grid': Grid,
  'lucide-layout': Layout,
  'lucide-sidebar': Sidebar,
  'lucide-layers': Layers,
  'lucide-filter': Filter,
  'lucide-magic': Magic,
  'lucide-wand': Wand,

  // Common Elements
  'lucide-star': Star,
  'lucide-heart': Heart,
  'lucide-trophy': Trophy,
  'lucide-award': Award,
  'lucide-gift': Gift,

  // Shopping & Finance
  'lucide-package': Package,
  'lucide-shopping-bag': ShoppingBag,
  'lucide-shopping-cart': ShoppingCart,
  'lucide-credit-card': CreditCard,
  'lucide-wallet': Wallet,
  'lucide-dollar-sign': DollarSign,
  'lucide-receipt': Receipt,

  // Charts & Analytics
  'lucide-chart-bar': ChartBar,
  'lucide-chart-line': ChartLine,
  'lucide-chart-pie': ChartPie,
  'lucide-activity': Activity,
  'lucide-pulse': Pulse,

  // Hardware & Devices
  'lucide-thermometer': Thermometer,
  'lucide-droplet': Droplet,
  'lucide-database': Database,
  'lucide-server': Server,
  'lucide-terminal': Terminal,
  'lucide-code': Code,
  'lucide-cpu': Cpu,
  'lucide-chip': Chip,
  'lucide-battery': Battery,
  'lucide-plug': Plug,
  'lucide-wifi': Wifi,
  'lucide-bluetooth': Bluetooth,
  'lucide-signal': Signal,
  'lucide-power': Power,

  // Communication
  'lucide-mail': Mail,
  'lucide-message-circle': MessageCircle,
  'lucide-message-square': MessageSquare,
  'lucide-send': Send,
  'lucide-share': Share,
  'lucide-link': Link,
  'lucide-unlink': LinkUnlink,
  'lucide-paperclip': Paperclip,
  'lucide-hash': Hash,

  // Lists & Tasks
  'lucide-list': List,
  'lucide-list-checks': ListChecks,
  'lucide-check-square': CheckSquare,
  'lucide-check': Check,
  'lucide-x': X,
  'lucide-plus': Plus,
  'lucide-minus': Minus,
  'lucide-divide': Divide,
  'lucide-equal': Equal,
  'lucide-percent': Percent,
  'lucide-at-sign': AtSign,

  // Search & View
  'lucide-search': Search,
  'lucide-zoom-in': ZoomIn,
  'lucide-zoom-out': ZoomOut,
  'lucide-maximize': Maximize,
  'lucide-minimize': Minimize,
  'lucide-expand': Expand,
  'lucide-shrink': Shrink,

  // Navigation Arrows
  'lucide-arrow-up': ArrowUp,
  'lucide-arrow-down': ArrowDown,
  'lucide-arrow-left': ArrowLeft,
  'lucide-arrow-right': ArrowRight,
  'lucide-chevron-up': ChevronUp,
  'lucide-chevron-down': ChevronDown,
  'lucide-chevron-left': ChevronLeft,
  'lucide-chevron-right': ChevronRight,

  // Time & Notifications
  'lucide-clock': Clock,
  'lucide-calendar': Calendar,
  'lucide-bell': Bell,

  // Information & Alerts
  'lucide-info': Info,
  'lucide-alert-circle': AlertCircle,
  'lucide-alert-triangle': AlertTriangle,
  'lucide-alert-octagon': AlertOctagon,
  'lucide-help': Help,

  // Security & Access
  'lucide-eye': Eye,
  'lucide-eye-off': EyeOff,
  'lucide-lock': Lock,
  'lucide-unlock': Unlock,
  'lucide-key': Key,

  // Settings & Configuration
  'lucide-cog': Cog,
  'lucide-settings-2': Settings2,

  // Users & Accounts
  'lucide-user': User,
  'lucide-users': Users,
  'lucide-user-plus': UserPlus,
  'lucide-user-minus': UserMinus,
  'lucide-user-check': UserCheck,
  'lucide-user-x': UserX,
};
