
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    # Habilitar gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location = /robots.txt {
        proxy_pass http://php:80/seo/robots.txt;
        proxy_set_header Host $host;
    }

    location = /sitemap.xml {
        proxy_pass http://php:80/seo/sitemap.xml;
        proxy_set_header Host $host;
    }

    location /sitemaps/ {
        proxy_pass http://php:80/seo/sitemaps/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    # Configuración para archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
    }
}
