
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjswxvsfwqnwgrpqctkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqc3d4dnNmd3Fud2dycHFjdGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjI1NTIsImV4cCI6MjA1ODEzODU1Mn0.r0fY3CVjYIV4bCHm7QjdQngw0iH0MkVnI5m8bGCZ3Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Simple test to verify connection
export const testSupabaseConnection = async () => {
  try {
    // Test connection by trying to get a list of tables
    const { data, error } = await supabase
      .from('products')
      .select('*')
      .limit(1);
    
    if (error) {
      console.error('Supabase connection error:', error);
      return { success: false, message: error.message, error };
    }
    
    console.log('Supabase connection successful:', data);
    return { success: true, data };
  } catch (err) {
    console.error('Unexpected error testing Supabase connection:', err);
    return { success: false, message: 'Unexpected error', error: err };
  }
};
