export type PhoneCountryOption = {
    code: string;
    name: string;
    dialCode: string;
    formatGroups: readonly number[];
};

export const PHONE_COUNTRIES: readonly PhoneCountryOption[] = [
    { code: "AF", name: "Afganistán", dialCode: "+93", formatGroups: [2, 3, 4] },
    { code: "AL", name: "Albania", dialCode: "+355", formatGroups: [2, 3, 4] },
    { code: "DE", name: "Alemania", dialCode: "+49", formatGroups: [2, 9] },
    { code: "AD", name: "Andorra", dialCode: "+376", formatGroups: [3, 3] },
    { code: "AO", name: "Angola", dialCode: "+244", formatGroups: [3, 3, 3] },
    { code: "AI", name: "Anguila", dialCode: "+1", formatGroups: [10] },
    { code: "AG", name: "Antigua y Barbuda", dialCode: "+1", formatGroups: [10] },
    { code: "SA", name: "Arabia Saudí", dialCode: "+966", formatGroups: [2, 3, 4] },
    { code: "DZ", name: "Argelia", dialCode: "+213", formatGroups: [3, 2, 2, 2] },
    { code: "AR", name: "Argentina", dialCode: "+54", formatGroups: [2, 2, 4, 4] },
    { code: "AM", name: "Armenia", dialCode: "+374", formatGroups: [2, 6] },
    { code: "AW", name: "Aruba", dialCode: "+297", formatGroups: [3, 4] },
    { code: "AU", name: "Australia", dialCode: "+61", formatGroups: [3, 3, 3] },
    { code: "AT", name: "Austria", dialCode: "+43", formatGroups: [3, 6] },
    { code: "AZ", name: "Azerbaiyán", dialCode: "+994", formatGroups: [2, 3, 2, 2] },
    { code: "BS", name: "Bahamas", dialCode: "+1", formatGroups: [10] },
    { code: "BD", name: "Bangladés", dialCode: "+880", formatGroups: [3, 7] },
    { code: "BB", name: "Barbados", dialCode: "+1", formatGroups: [10] },
    { code: "BH", name: "Baréin", dialCode: "+973", formatGroups: [4, 4] },
    { code: "BE", name: "Bélgica", dialCode: "+32", formatGroups: [3, 2, 2, 2] },
    { code: "BZ", name: "Belice", dialCode: "+501", formatGroups: [3, 4] },
    { code: "BJ", name: "Benín", dialCode: "+229", formatGroups: [2, 2, 2, 2, 2] },
    { code: "BM", name: "Bermudas", dialCode: "+1", formatGroups: [10] },
    { code: "BY", name: "Bielorrusia", dialCode: "+375", formatGroups: [2, 3, 2, 2] },
    { code: "BO", name: "Bolivia", dialCode: "+591", formatGroups: [8] },
    { code: "BA", name: "Bosnia y Herzegovina", dialCode: "+387", formatGroups: [2, 3, 3] },
    { code: "BW", name: "Botsuana", dialCode: "+267", formatGroups: [2, 3, 3] },
    { code: "BR", name: "Brasil", dialCode: "+55", formatGroups: [2, 5, 4] },
    { code: "BN", name: "Brunéi", dialCode: "+673", formatGroups: [3, 4] },
    { code: "BG", name: "Bulgaria", dialCode: "+359", formatGroups: [2, 3, 3] },
    { code: "BF", name: "Burkina Faso", dialCode: "+226", formatGroups: [2, 2, 2, 2] },
    { code: "BI", name: "Burundi", dialCode: "+257", formatGroups: [2, 2, 2, 2] },
    { code: "BT", name: "Bután", dialCode: "+975", formatGroups: [2, 2, 2, 2] },
    { code: "CV", name: "Cabo Verde", dialCode: "+238", formatGroups: [3, 2, 2] },
    { code: "KH", name: "Camboya", dialCode: "+855", formatGroups: [2, 3, 3] },
    { code: "CM", name: "Camerún", dialCode: "+237", formatGroups: [1, 2, 2, 2, 2] },
    { code: "CA", name: "Canadá", dialCode: "+1", formatGroups: [10] },
    { code: "BQ", name: "Caribe neerlandés", dialCode: "+599", formatGroups: [7] },
    { code: "QA", name: "Catar", dialCode: "+974", formatGroups: [4, 4] },
    { code: "TD", name: "Chad", dialCode: "+235", formatGroups: [2, 2, 2, 2] },
    { code: "CZ", name: "Chequia", dialCode: "+420", formatGroups: [3, 3, 3] },
    { code: "CL", name: "Chile", dialCode: "+56", formatGroups: [1, 4, 4] },
    { code: "CN", name: "China", dialCode: "+86", formatGroups: [3, 4, 4] },
    { code: "CY", name: "Chipre", dialCode: "+357", formatGroups: [2, 6] },
    { code: "VA", name: "Ciudad del Vaticano", dialCode: "+39", formatGroups: [10] },
    { code: "CO", name: "Colombia", dialCode: "+57", formatGroups: [3, 7] },
    { code: "KM", name: "Comoras", dialCode: "+269", formatGroups: [3, 2, 2] },
    { code: "CG", name: "Congo", dialCode: "+242", formatGroups: [2, 3, 4] },
    { code: "KP", name: "Corea del Norte", dialCode: "+850", formatGroups: [3, 3, 4] },
    { code: "KR", name: "Corea del Sur", dialCode: "+82", formatGroups: [2, 4, 4] },
    { code: "CR", name: "Costa Rica", dialCode: "+506", formatGroups: [4, 4] },
    { code: "CI", name: "Côte d’Ivoire", dialCode: "+225", formatGroups: [2, 2, 2, 4] },
    { code: "HR", name: "Croacia", dialCode: "+385", formatGroups: [2, 3, 4] },
    { code: "CU", name: "Cuba", dialCode: "+53", formatGroups: [2, 6] },
    { code: "CW", name: "Curazao", dialCode: "+599", formatGroups: [1, 3, 4] },
    { code: "DK", name: "Dinamarca", dialCode: "+45", formatGroups: [2, 2, 2, 2] },
    { code: "DM", name: "Dominica", dialCode: "+1", formatGroups: [10] },
    { code: "EC", name: "Ecuador", dialCode: "+593", formatGroups: [2, 3, 4] },
    { code: "EG", name: "Egipto", dialCode: "+20", formatGroups: [2, 8] },
    { code: "SV", name: "El Salvador", dialCode: "+503", formatGroups: [4, 4] },
    { code: "AE", name: "Emiratos Árabes Unidos", dialCode: "+971", formatGroups: [2, 3, 4] },
    { code: "ER", name: "Eritrea", dialCode: "+291", formatGroups: [1, 3, 3] },
    { code: "SK", name: "Eslovaquia", dialCode: "+421", formatGroups: [3, 3, 3] },
    { code: "SI", name: "Eslovenia", dialCode: "+386", formatGroups: [2, 3, 3] },
    { code: "ES", name: "España", dialCode: "+34", formatGroups: [3, 2, 2, 2] },
    { code: "US", name: "Estados Unidos", dialCode: "+1", formatGroups: [3, 3, 4] },
    { code: "EE", name: "Estonia", dialCode: "+372", formatGroups: [4, 4] },
    { code: "SZ", name: "Esuatini", dialCode: "+268", formatGroups: [4, 4] },
    { code: "ET", name: "Etiopía", dialCode: "+251", formatGroups: [2, 3, 4] },
    { code: "PH", name: "Filipinas", dialCode: "+63", formatGroups: [3, 3, 4] },
    { code: "FI", name: "Finlandia", dialCode: "+358", formatGroups: [2, 7] },
    { code: "FJ", name: "Fiyi", dialCode: "+679", formatGroups: [3, 4] },
    { code: "FR", name: "Francia", dialCode: "+33", formatGroups: [1, 2, 2, 2, 2] },
    { code: "GA", name: "Gabón", dialCode: "+241", formatGroups: [2, 2, 2, 2] },
    { code: "GM", name: "Gambia", dialCode: "+220", formatGroups: [3, 4] },
    { code: "GE", name: "Georgia", dialCode: "+995", formatGroups: [3, 2, 2, 2] },
    { code: "GH", name: "Ghana", dialCode: "+233", formatGroups: [2, 3, 4] },
    { code: "GI", name: "Gibraltar", dialCode: "+350", formatGroups: [8] },
    { code: "GD", name: "Granada", dialCode: "+1", formatGroups: [10] },
    { code: "GR", name: "Grecia", dialCode: "+30", formatGroups: [2, 4, 4] },
    { code: "GL", name: "Groenlandia", dialCode: "+299", formatGroups: [2, 2, 2] },
    { code: "GP", name: "Guadalupe", dialCode: "+590", formatGroups: [3, 2, 2, 2] },
    { code: "GU", name: "Guam", dialCode: "+1", formatGroups: [10] },
    { code: "GT", name: "Guatemala", dialCode: "+502", formatGroups: [4, 4] },
    { code: "GF", name: "Guayana Francesa", dialCode: "+594", formatGroups: [3, 2, 2, 2] },
    { code: "GG", name: "Guernesey", dialCode: "+44", formatGroups: [10] },
    { code: "GN", name: "Guinea", dialCode: "+224", formatGroups: [3, 2, 2, 2] },
    { code: "GQ", name: "Guinea Ecuatorial", dialCode: "+240", formatGroups: [3, 3, 3] },
    { code: "GW", name: "Guinea-Bisáu", dialCode: "+245", formatGroups: [3, 3, 3] },
    { code: "GY", name: "Guyana", dialCode: "+592", formatGroups: [3, 4] },
    { code: "HT", name: "Haití", dialCode: "+509", formatGroups: [2, 2, 4] },
    { code: "HN", name: "Honduras", dialCode: "+504", formatGroups: [4, 4] },
    { code: "HU", name: "Hungría", dialCode: "+36", formatGroups: [2, 3, 4] },
    { code: "IN", name: "India", dialCode: "+91", formatGroups: [4, 3, 3] },
    { code: "ID", name: "Indonesia", dialCode: "+62", formatGroups: [3, 3, 3] },
    { code: "IQ", name: "Irak", dialCode: "+964", formatGroups: [3, 3, 4] },
    { code: "IR", name: "Irán", dialCode: "+98", formatGroups: [3, 3, 4] },
    { code: "IE", name: "Irlanda", dialCode: "+353", formatGroups: [2, 3, 4] },
    { code: "AC", name: "Isla de la Ascensión", dialCode: "+247", formatGroups: [5] },
    { code: "IM", name: "Isla de Man", dialCode: "+44", formatGroups: [10] },
    { code: "CX", name: "Isla de Navidad", dialCode: "+61", formatGroups: [9] },
    { code: "NF", name: "Isla Norfolk", dialCode: "+672", formatGroups: [1, 5] },
    { code: "IS", name: "Islandia", dialCode: "+354", formatGroups: [3, 4] },
    { code: "AX", name: "Islas Aland", dialCode: "+358", formatGroups: [9] },
    { code: "KY", name: "Islas Caimán", dialCode: "+1", formatGroups: [10] },
    { code: "CC", name: "Islas Cocos", dialCode: "+61", formatGroups: [9] },
    { code: "CK", name: "Islas Cook", dialCode: "+682", formatGroups: [2, 3] },
    { code: "FO", name: "Islas Feroe", dialCode: "+298", formatGroups: [6] },
    { code: "FK", name: "Islas Malvinas", dialCode: "+500", formatGroups: [5] },
    { code: "MP", name: "Islas Marianas del Norte", dialCode: "+1", formatGroups: [10] },
    { code: "MH", name: "Islas Marshall", dialCode: "+692", formatGroups: [3, 4] },
    { code: "SB", name: "Islas Salomón", dialCode: "+677", formatGroups: [2, 5] },
    { code: "TC", name: "Islas Turcas y Caicos", dialCode: "+1", formatGroups: [10] },
    { code: "VG", name: "Islas Vírgenes Británicas", dialCode: "+1", formatGroups: [10] },
    { code: "VI", name: "Islas Vírgenes de EE. UU.", dialCode: "+1", formatGroups: [10] },
    { code: "IL", name: "Israel", dialCode: "+972", formatGroups: [2, 3, 4] },
    { code: "IT", name: "Italia", dialCode: "+39", formatGroups: [2, 4, 4] },
    { code: "JM", name: "Jamaica", dialCode: "+1", formatGroups: [10] },
    { code: "JP", name: "Japón", dialCode: "+81", formatGroups: [2, 4, 4] },
    { code: "JE", name: "Jersey", dialCode: "+44", formatGroups: [10] },
    { code: "JO", name: "Jordania", dialCode: "+962", formatGroups: [1, 4, 4] },
    { code: "KZ", name: "Kazajistán", dialCode: "+7", formatGroups: [10] },
    { code: "KE", name: "Kenia", dialCode: "+254", formatGroups: [3, 6] },
    { code: "KG", name: "Kirguistán", dialCode: "+996", formatGroups: [3, 3, 3] },
    { code: "KI", name: "Kiribati", dialCode: "+686", formatGroups: [8] },
    { code: "XK", name: "Kosovo", dialCode: "+383", formatGroups: [2, 3, 3] },
    { code: "KW", name: "Kuwait", dialCode: "+965", formatGroups: [4, 4] },
    { code: "LA", name: "Laos", dialCode: "+856", formatGroups: [2, 2, 3, 3] },
    { code: "LS", name: "Lesoto", dialCode: "+266", formatGroups: [4, 4] },
    { code: "LV", name: "Letonia", dialCode: "+371", formatGroups: [2, 3, 3] },
    { code: "LB", name: "Líbano", dialCode: "+961", formatGroups: [2, 3, 3] },
    { code: "LR", name: "Liberia", dialCode: "+231", formatGroups: [2, 3, 4] },
    { code: "LY", name: "Libia", dialCode: "+218", formatGroups: [2, 7] },
    { code: "LI", name: "Liechtenstein", dialCode: "+423", formatGroups: [3, 3, 3] },
    { code: "LT", name: "Lituania", dialCode: "+370", formatGroups: [2, 6] },
    { code: "LU", name: "Luxemburgo", dialCode: "+352", formatGroups: [2, 2, 2, 3] },
    { code: "MK", name: "Macedonia del Norte", dialCode: "+389", formatGroups: [2, 3, 3] },
    { code: "MG", name: "Madagascar", dialCode: "+261", formatGroups: [2, 2, 3, 2] },
    { code: "MY", name: "Malasia", dialCode: "+60", formatGroups: [2, 3, 4] },
    { code: "MW", name: "Malaui", dialCode: "+265", formatGroups: [3, 2, 2, 2] },
    { code: "MV", name: "Maldivas", dialCode: "+960", formatGroups: [3, 4] },
    { code: "ML", name: "Mali", dialCode: "+223", formatGroups: [2, 2, 2, 2] },
    { code: "MT", name: "Malta", dialCode: "+356", formatGroups: [4, 4] },
    { code: "MA", name: "Marruecos", dialCode: "+212", formatGroups: [1, 2, 2, 2, 2] },
    { code: "MQ", name: "Martinica", dialCode: "+596", formatGroups: [3, 2, 2, 2] },
    { code: "MU", name: "Mauricio", dialCode: "+230", formatGroups: [4, 4] },
    { code: "MR", name: "Mauritania", dialCode: "+222", formatGroups: [2, 2, 2, 2] },
    { code: "YT", name: "Mayotte", dialCode: "+262", formatGroups: [9] },
    { code: "MX", name: "México", dialCode: "+52", formatGroups: [2, 4, 4] },
    { code: "FM", name: "Micronesia", dialCode: "+691", formatGroups: [3, 4] },
    { code: "MD", name: "Moldavia", dialCode: "+373", formatGroups: [2, 3, 3] },
    { code: "MC", name: "Mónaco", dialCode: "+377", formatGroups: [1, 2, 2, 2, 2] },
    { code: "MN", name: "Mongolia", dialCode: "+976", formatGroups: [4, 4] },
    { code: "ME", name: "Montenegro", dialCode: "+382", formatGroups: [2, 3, 3] },
    { code: "MS", name: "Montserrat", dialCode: "+1", formatGroups: [10] },
    { code: "MZ", name: "Mozambique", dialCode: "+258", formatGroups: [2, 3, 4] },
    { code: "MM", name: "Myanmar (Birmania)", dialCode: "+95", formatGroups: [1, 3, 4] },
    { code: "NA", name: "Namibia", dialCode: "+264", formatGroups: [2, 3, 4] },
    { code: "NR", name: "Nauru", dialCode: "+674", formatGroups: [3, 4] },
    { code: "NP", name: "Nepal", dialCode: "+977", formatGroups: [3, 7] },
    { code: "NI", name: "Nicaragua", dialCode: "+505", formatGroups: [4, 4] },
    { code: "NE", name: "Níger", dialCode: "+227", formatGroups: [2, 2, 2, 2] },
    { code: "NG", name: "Nigeria", dialCode: "+234", formatGroups: [3, 3, 4] },
    { code: "NU", name: "Niue", dialCode: "+683", formatGroups: [3, 4] },
    { code: "NO", name: "Noruega", dialCode: "+47", formatGroups: [2, 2, 2, 2] },
    { code: "NC", name: "Nueva Caledonia", dialCode: "+687", formatGroups: [2, 2, 2] },
    { code: "NZ", name: "Nueva Zelanda", dialCode: "+64", formatGroups: [3, 3, 3] },
    { code: "OM", name: "Omán", dialCode: "+968", formatGroups: [4, 4] },
    { code: "NL", name: "Países Bajos", dialCode: "+31", formatGroups: [1, 8] },
    { code: "PK", name: "Pakistán", dialCode: "+92", formatGroups: [3, 7] },
    { code: "PW", name: "Palaos", dialCode: "+680", formatGroups: [3, 4] },
    { code: "PA", name: "Panamá", dialCode: "+507", formatGroups: [4, 4] },
    { code: "PG", name: "Papúa Nueva Guinea", dialCode: "+675", formatGroups: [4, 4] },
    { code: "PY", name: "Paraguay", dialCode: "+595", formatGroups: [2, 3, 4] },
    { code: "PE", name: "Perú", dialCode: "+51", formatGroups: [3, 3, 3] },
    { code: "PF", name: "Polinesia Francesa", dialCode: "+689", formatGroups: [2, 2, 2, 2] },
    { code: "PL", name: "Polonia", dialCode: "+48", formatGroups: [3, 3, 3] },
    { code: "PT", name: "Portugal", dialCode: "+351", formatGroups: [3, 3, 3] },
    { code: "PR", name: "Puerto Rico", dialCode: "+1", formatGroups: [10] },
    { code: "HK", name: "RAE de Hong Kong (China)", dialCode: "+852", formatGroups: [4, 4] },
    { code: "MO", name: "RAE de Macao (China)", dialCode: "+853", formatGroups: [4, 4] },
    { code: "GB", name: "Reino Unido", dialCode: "+44", formatGroups: [4, 6] },
    { code: "CF", name: "República Centroafricana", dialCode: "+236", formatGroups: [2, 2, 2, 2] },
    { code: "CD", name: "República Democrática del Congo", dialCode: "+243", formatGroups: [3, 3, 3] },
    { code: "DO", name: "República Dominicana", dialCode: "+1", formatGroups: [10] },
    { code: "RE", name: "Reunión", dialCode: "+262", formatGroups: [3, 2, 2, 2] },
    { code: "RW", name: "Ruanda", dialCode: "+250", formatGroups: [3, 3, 3] },
    { code: "RO", name: "Rumanía", dialCode: "+40", formatGroups: [3, 3, 3] },
    { code: "RU", name: "Rusia", dialCode: "+7", formatGroups: [3, 3, 2, 2] },
    { code: "EH", name: "Sáhara Occidental", dialCode: "+212", formatGroups: [9] },
    { code: "WS", name: "Samoa", dialCode: "+685", formatGroups: [2, 5] },
    { code: "AS", name: "Samoa Americana", dialCode: "+1", formatGroups: [10] },
    { code: "BL", name: "San Bartolomé", dialCode: "+590", formatGroups: [9] },
    { code: "KN", name: "San Cristóbal y Nieves", dialCode: "+1", formatGroups: [10] },
    { code: "SM", name: "San Marino", dialCode: "+378", formatGroups: [2, 2, 2, 2] },
    { code: "MF", name: "San Martín", dialCode: "+590", formatGroups: [9] },
    { code: "PM", name: "San Pedro y Miquelón", dialCode: "+508", formatGroups: [2, 2, 2] },
    { code: "VC", name: "San Vicente y las Granadinas", dialCode: "+1", formatGroups: [10] },
    { code: "SH", name: "Santa Elena", dialCode: "+290", formatGroups: [5] },
    { code: "LC", name: "Santa Lucía", dialCode: "+1", formatGroups: [10] },
    { code: "ST", name: "Santo Tomé y Príncipe", dialCode: "+239", formatGroups: [3, 4] },
    { code: "SN", name: "Senegal", dialCode: "+221", formatGroups: [2, 3, 2, 2] },
    { code: "RS", name: "Serbia", dialCode: "+381", formatGroups: [3, 6] },
    { code: "SC", name: "Seychelles", dialCode: "+248", formatGroups: [1, 3, 3] },
    { code: "SL", name: "Sierra Leona", dialCode: "+232", formatGroups: [2, 6] },
    { code: "SG", name: "Singapur", dialCode: "+65", formatGroups: [4, 4] },
    { code: "SX", name: "Sint Maarten", dialCode: "+1", formatGroups: [10] },
    { code: "SY", name: "Siria", dialCode: "+963", formatGroups: [3, 3, 3] },
    { code: "SO", name: "Somalia", dialCode: "+252", formatGroups: [1, 7] },
    { code: "LK", name: "Sri Lanka", dialCode: "+94", formatGroups: [2, 3, 4] },
    { code: "ZA", name: "Sudáfrica", dialCode: "+27", formatGroups: [2, 3, 4] },
    { code: "SD", name: "Sudán", dialCode: "+249", formatGroups: [2, 3, 4] },
    { code: "SS", name: "Sudán del Sur", dialCode: "+211", formatGroups: [3, 3, 3] },
    { code: "SE", name: "Suecia", dialCode: "+46", formatGroups: [2, 3, 2, 2] },
    { code: "CH", name: "Suiza", dialCode: "+41", formatGroups: [2, 3, 2, 2] },
    { code: "SR", name: "Surinam", dialCode: "+597", formatGroups: [3, 4] },
    { code: "SJ", name: "Svalbard y Jan Mayen", dialCode: "+47", formatGroups: [8] },
    { code: "TH", name: "Tailandia", dialCode: "+66", formatGroups: [2, 3, 4] },
    { code: "TW", name: "Taiwán", dialCode: "+886", formatGroups: [1, 4, 4] },
    { code: "TZ", name: "Tanzania", dialCode: "+255", formatGroups: [3, 3, 3] },
    { code: "TJ", name: "Tayikistán", dialCode: "+992", formatGroups: [2, 3, 4] },
    { code: "IO", name: "Territorio Británico del Océano Índico", dialCode: "+246", formatGroups: [3, 4] },
    { code: "PS", name: "Territorios Palestinos", dialCode: "+970", formatGroups: [3, 3, 3] },
    { code: "TL", name: "Timor-Leste", dialCode: "+670", formatGroups: [4, 4] },
    { code: "TG", name: "Togo", dialCode: "+228", formatGroups: [2, 2, 2, 2] },
    { code: "TK", name: "Tokelau", dialCode: "+690", formatGroups: [4] },
    { code: "TO", name: "Tonga", dialCode: "+676", formatGroups: [3, 4] },
    { code: "TT", name: "Trinidad y Tobago", dialCode: "+1", formatGroups: [10] },
    { code: "TA", name: "Tristán de Acuña", dialCode: "+290", formatGroups: [4] },
    { code: "TN", name: "Túnez", dialCode: "+216", formatGroups: [2, 3, 3] },
    { code: "TM", name: "Turkmenistán", dialCode: "+993", formatGroups: [2, 6] },
    { code: "TR", name: "Turquía", dialCode: "+90", formatGroups: [3, 3, 2, 2] },
    { code: "TV", name: "Tuvalu", dialCode: "+688", formatGroups: [2, 4] },
    { code: "UA", name: "Ucrania", dialCode: "+380", formatGroups: [4, 5] },
    { code: "UG", name: "Uganda", dialCode: "+256", formatGroups: [3, 6] },
    { code: "UY", name: "Uruguay", dialCode: "+598", formatGroups: [2, 3, 3] },
    { code: "UZ", name: "Uzbekistán", dialCode: "+998", formatGroups: [2, 3, 2, 2] },
    { code: "VU", name: "Vanuatu", dialCode: "+678", formatGroups: [3, 4] },
    { code: "VE", name: "Venezuela", dialCode: "+58", formatGroups: [3, 7] },
    { code: "VN", name: "Vietnam", dialCode: "+84", formatGroups: [3, 3, 3] },
    { code: "WF", name: "Wallis y Futuna", dialCode: "+681", formatGroups: [2, 2, 2] },
    { code: "YE", name: "Yemen", dialCode: "+967", formatGroups: [3, 3, 3] },
    { code: "DJ", name: "Yibuti", dialCode: "+253", formatGroups: [2, 2, 2, 2] },
    { code: "ZM", name: "Zambia", dialCode: "+260", formatGroups: [2, 7] },
    { code: "ZW", name: "Zimbabue", dialCode: "+263", formatGroups: [2, 3, 4] },
];
